// Generated by Wrangler

import { AIChatHandler } from "./src/chatHandler";

// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
type Env = {
	AI_CHAT_HANDLER: DurableObjectNamespace<AIChatHandler>;
	AI: Ai
	CHATBOT_KV: KVNamespace;
}

